### ISSUE TITLE
Jumbled text on copying

### ISSUE THREAD

**Issue by j9d3it** [dacer/Kata#2]
Sometimes when copying text it gets jumbled and overlaps. Here's an example:

http://i.imgur.com/QPl2WHC.jpg

Here's the original text. It's not jumbled when copying from here.

朝からソワソワしとるおっさんです(゜ρ゜)
ここで昨年のニコ生ベストコメントでも

It's usually not jumbled after copying directly from LINE when showing in the pop-up, however after selecting a word in the pop-up it gets jumbled.

http://i.imgur.com/jn9o0Pn.jpg

**Comment by dacer** [comment]
This bug is not easy to reproduce for me, so it maybe need some time to fix

**Comment by dacer** [comment]
Hi, I have rewritten part of code and maybe can fix this bug, you can try the 1.0.0-Beta.9 version
