### ISSUE TITLE
Only reads link when copying any block of text that includes a link

### ISSUE THREAD

**Issue by j9d3it** [dacer/Kata#3]
When copying any text that includes a link, Kata ignores any text and tries to read the link embedded in the text. This is of particular annoyance on Tweets, which have shortened links that cannot be directly read. Often, I just want to read the Tweet itself instead of the article that accompanies it. This is also an issue on Tweets with images, in which Kata tries to parse the link to the image as containing text which it does not.

Here is an example of the first behavior.

https://streamable.com/rmv7e

And here is another Tweet which, when copied, has the same issue. Except that this time it's not an article that's linked, just images.

https://twitter.com/lr_ole/status/1032585811529674757

My suggestion is to have an option to completely disable the link parsing feature, or ignore links if they are part of a larger block of text.

**Comment by dacer** [comment]
Thank you for your feedback.

This issue will be fixed in the next version (1.0.0-Beta.7).
